### ISSUE TITLE
Init-db container doesn't see posgresql

### ISSUE THREAD

**Issue by TheFuzzyTech** [mvitale1989/helm-taiga#7]
I'm relatively new to kubernetes so this is more than likely a 'me' problem. I'm struggling to get this chart running. When the init-db container runs it never see's the db as up. I've tried setting dbHost to ${release_name}-postgresql and I've also tried just entering the value of the pod name manually (release-postresql-0). I'm not sure what else could be wrong at this point. I'm trying to run this in a local k8s cluster. Below is a sanitized values.yaml

```yaml
### Default values for taiga.

image:
  repository: mvitale1989/docker-taiga
  tag: "20191031-4.2.14"
  initRepository: alpine
  initTag: 3.7
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: 
    kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
  - taiga.org.com
  tls: 
  - secretName: taiga-tls
    hosts:
    - taiga.org.com
### Parameters for the taiga service
###
taiga:

  ### The name on which the taiga backend API server will be accessible. In this chart, it's the same name you will use to
  ### access the frontend.  Notes:
  ### - Must be formatted exactly as you would type the hostname part of the URL in a browser, including the port number if needed.
  ### - Must be reachable by ALL clients using the service. See F.A.Q. in the readme, for more informations.
  ###
  apiserver: taiga.org.com

  ### Whether taiga is behind a TLS termination; if using a TLS ingress, set this to true.
  ###
  behindTlsProxy: true

  ### Database access parameters
  ### If deploying postgres, the dbHost should be `${release_name}-postgresql`
  ###
  dbHost: my-taiga-postgresql-0
  dbName: taiga
  dbUser: taiga
  dbPassword: "password"

  ### If you enable email, also uncomment and configure the parameters below
  ###
  emailEnabled: false
  # emailFrom: "taiga@mycompany.net"
  # emailUseTls: true
  # emailSmtpHost: "smtp.example.com"
  # emailSmtpPort: 587
  # emailSmtpUser: "user@example.com"
  # emailSmtpPassword: ""
  ldap:
    enabled: False
    use_tls: False
    ldap_server: ldap://<ldap_server_host_name>
    port: 389
    bind_dn: "cn=something,ou=admins,ou=theouhere,ou=auth,o=ethz,c=ch"
    base_dn: "basednhere"
    password: "changeme"
    username_attribute: "uid"
    email_attribute: "mail"
    full_name_attribute: "displayName"
    fallback: "normal"
    save_password: False
    filter: "(mail=*)"
  ### Configure taiga-back's secret key
  ### If omitted, a random alphanumeric string of 10 characters will be generated
  ###
  # secretKey: "changeme"


### Persistent volume and database configuration for the taiga service
###
persistence:

  ### Whether or not you want this chart to provision the database for you
  ### Database parameters must be specified under the `postgres` value
  ###
  deployPostgres: true

  ### If you don't want persistence for the taiga media storage, disable this
  ###
  enabled: true
  size: 8Gi
  accessMode: ReadWriteOnce
  annotations:
    "helm.sh/resource-policy": keep

  ## StorageClass for the provisioned PVC.
  ##
  storageClass: ""

  ### If you prefer using a PVC defined outside of this chart instead, uncomment this
  ### Requires `persistence.enabled: true`
  ###
  # existingClaim: ""


### Any stable/postgres values can be defined here
###
postgresql:

  ### Create a postgres user, password and database
  ###
  postgresqlUsername: "taiga"
  postgresqlPassword: "password"
  postgresqlDatabase: "taiga"

  persistence:
    enabled: true
    size: 2Gi
    annotations:
      "helm.sh/resource-policy": keep

    ### StorageClass for the provisioned PVC.
    ###
    storageClass: ""

    ### If you prefer using a PVC defined outside of this chart instead, uncomment this
    ### Requires `postgresql.persistence.enabled: true`
    ###
    # existingClaim: ""
```
